### ISSUE TITLE
Looked promising but...

### ISSUE THREAD

**Issue by bwbecker** [Vimux/Mainroad#12]
Mainroad looked really promising but I couldn't for the life of me get my pages to show up.  It was definitely picking up the theme -- I could enter the URL of the pages and have them show, the authorbox was there, etc.  But nothing on the main page other than theme-related stuff, not TOC, etc.

Switched to hugo_theme_robust and had instant gratification; no other changes to my site other than switching the --theme parameter when launching the server.

You've obviously put a lot of work into this, the sample site looks great, but I feel like there's something (likely simple) that isn't mentioned in the documentation.

**Comment by bwbecker** [comment]
Found one issue.  Someplace in the code there is an assumption that content is in `content/post` whereas I had it in `content/posts`.

Are there other content directories that are treated specially?

Leaving this open because I think it needs documentation.

**Comment by matheusrocha89** [comment]
@bwbecker I feel the same, lack of doc and I think the maintainer is not interest on the project anymore. I will use my fork and make updates on it. Add social share and other stuffs.

**Comment by matheusrocha89** [comment]
@bwbecker I was wrong, he is interested, maybe he is just busy. I will open all the PR's to the project and try to make it better. Please Open Issues when you find a bug, some lack on docs, and a feature request.

**Comment by Vimux** [comment]
@bwbecker,

I regret that Mainroad is complex to understand and configure. So it's time to write documentation or FAQ. If you write about everything that appears unclear to you, it would help me to start writing documentation.

In the current state, Mainroad include in list "post" type only.
Why "post" instead "posts" or something else? Because [HugoBasicExample](https://github.com/spf13/HugoBasicExample) uses this type of notation for notes by-default. I use slightly modified content from HugoBasicExample with exactly the same type.

@matheusrocha89,

I have not lost interest in the subject. Open sourse my hobby, not a job. I don't have much time to deal with constantly, day after day. When I have free time, I continue to improve Mainroad.

I planned a few changes this month.

**Comment by matheusrocha89** [comment]
@Vimux I undestand, I am contributing now because I'm on vacation. I want to help in any way I can and I understand you. I know how is it to work and have an O.S project (I am on of the maintainers of ng-cordova-oauth). I like the project and I will help you with features, issues and PR.

**Comment by henningsway** [comment]
This looks like a very nice project. A few questions from my side:
- is there a way to have a blog with multiple authors using this theme?
- would it easy to add a picture in the header?
- changing the colour scheme should be straingtforward?
Thank you. :)

**Comment by Vimux** [comment]
1. By default — no, but if you understand how Hugo works, I think you can do it.
2. Through config.toml - no, only through editing CSS (or HTML templates)
3. There's currently no easy way to change color scheme, only manual CSS editing

**Comment by Vimux** [comment]
Problem solved (long ago), so I close the issue.
