### ISSUE TITLE
Safari's cross-site-tracking option messes up rendering

### ISSUE THREAD

**Issue by Vermyndax** [Vimux/Mainroad#167]
When "Prevent cross-site tracking" is enabled on Safari 13.0.4 in Catalina and iOS 13.3, CSS fails to render properly with this theme. Disabling the option allows it to work.

**Comment by Vimux** [comment]
Can't reproduce.

* macOS Mojave (10.14.6) with Safari (Version 13.0.4 (14608.4.9.1.4)) and Safari Technology Preview (Release 98 (Safari 13.1,
WebKit 14609.1.13.4)) works correctly in both cases.
* Mobile Safari (iOS13.3) works correctly too.

Tested on [demo](https://hugothemes.gitlab.io/mainroad/).

Need more related data ([Reporting bugs](https://github.com/Vimux/Mainroad/blob/master/CONTRIBUTING.md#reporting-bugs)), otherwise I'll close this after two weeks of inactivity.

**Comment by Vermyndax** [comment]
It looks like this may have been related to Adsense. I took Adsense out of my site and it's working fine now. Safari was the only browser causing this issue when this option was enabled and Adsense was in the site... which makes sense. So, I don't think this is your bug.
