### ISSUE TITLE
How to display one single file (.md) instead of lists on the homepage?

### ISSUE THREAD

**Issue by grandnew** [Vimux/Mainroad#171]
Hi, all!
Mainroad is an excellent Hugo theme!
Recently, I'm going to make personal homepage based on Mainroad, like [this](https://www.luolc.com). This example is fantastic and I want to make a similar one.
But, I don't know what to do so that I can display one single file (.md) instead of lists on the homepage. Could you help me, please?
Thanks so much!

**Comment by imaderaya** [comment]
Hello;
replace the content of index.html in "themes/mainroad/" , by this:

```
{{ define "main" }}
<main class="main list" role="main">
	{{- with .Content }}
	<div class="content main__content clearfix">
		{{ . }}
	</div>
	{{- end }}
</main>
{{ end }}
```

then in the content folder create "_index.md" wich will hold your home page content.

good luck.

**Comment by Vimux** [comment]
In addition to the previous comment: if you don't want to touch theme files, take a look at the [Hugo Layout Lookup for Home Page](https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-home-page). Very briefly, you can add file this way: `<site-root>/layouts/index.html`.

**Comment by Vimux** [comment]
Summary before closing this issue. There are two main ways to display a single file instead of `mainSections` list on the homepage:

1. Create index.md file inside your content folder. You can use front matter params to disable unnecessary elements like authorbox. If you don't need anything special, this should be the preferred option.
1. Create custom homepage layout. If the default home layout is not good enough for you, then you can use this option to create your own.
