### ISSUE TITLE
BUG - youtube.svg not found

### ISSUE THREAD

**Issue by JoshTango** [Vimux/Mainroad#224]
I get this error:

ERROR 2020/07/20 14:33:04 failed to render pages: render of "home" failed: execute of template failed: template: index.html:48:6: executing "index.html" at <partial "sidebar.html" .>: error calling partial: execute of 
template failed: template: partials/sidebar.html:16:6: executing "partials/sidebar.html" at <partial $p $root>: error calling partial: "C:\*****************Mainroad-master\layouts\partials\widgets\social.html:82:8": execute of template failed: template: partials/widgets/social.html:82:8: executing "partials/widgets/social.html" at <partial .icon (dict "class" "widget-social__link-icon")>: error calling partial: partial "youtube.svg" not found

**Comment by Vimux** [comment]
As stated in CONTRIBUTING.md, **please do not use the issue tracker for personal support requests**. Perhaps you should read the documentation in the README carefully.

Closed and marked as invalid.

**Comment by JoshTango** [comment]
I just discovered the theme uses youtube.svg but there is no youtube.svg file present.
How is it a personal issue?
I added a youtube.svg file and it worked.

**Comment by Vimux** [comment]
> I just discovered the theme uses youtube.svg but there is no youtube.svg file present.

Then you can easily point me to the file(s) where exactly the theme is using youtube.svg file, right?

**Comment by JoshTango** [comment]
yes the config.toml

**Comment by JoshTango** [comment]
hmmm wait I copied that from the website example lol
so yes it still came from you lol

**Comment by Vimux** [comment]
> yes the config.toml

No, our demo site uses this file and generates successfully without any such errors.

> hmmm wait I copied that from the website example lol
> so yes it still came from you lol

Thus, you did not specify the specific file (not the section from the README), because there is only one mention of this SVG file: in the example config from README. And it becomes clear why you get this error if you read the README file carefully.

What happened in reality? You've copied the entire config from README, completely ignored the note below and [Social Widget: custom links](https://github.com/Vimux/Mainroad#social-widget-custom-links) section.

As I said earlier, it's invalid and would be locked right now.
