### ISSUE TITLE
Favicon support

### ISSUE THREAD

**Issue by hbergren** [Vimux/Mainroad#3]
How would I add a custom favicon to the theme? The documentation around Hugo is sparse as well. I've seen some themes handle this in a a custom way.

**Comment by Vimux** [comment]
Hi, @hbergren, I'm sorry for the long delay.

Just put a set of your favicons in static folder and add meta link in the head section of header.html. Something like this:

`<link rel="icon" href="{{ $.Site.BaseURL }}images/favicon.ico">`

**Comment by Vimux** [comment]
I added favicon. Now you can easily add your own favicon by replacing.

**Comment by enricodata** [comment]
when the theme is imported with blogdown::new_site(theme = "Vimux/Mainroad", theme_example = TRUE, force=TRUE)
 the favicon does not work. Not even the one provided with the files does not work as in https://themes.gohugo.io/theme/mainroad/
Maybe because in public/index.html the following code 	<link rel="shortcut icon" href="/favicon.ico"> does not point to the right folder?
