### ISSUE TITLE
localize date in post meta

### ISSUE THREAD

**Issue by LibreDrip** [Vimux/Mainroad#318]
I'm not too familiar with the go template engine yet, so according to https://gohugo.io/functions/dateformat/#datetime-formatting-layouts, in 
`layouts/partials/post_meta/date.html` I replaced 
`{{- .Date.Format (.Site.Params.dateformat | default "January 02, 2006") -}}` on line 5 with 
`{{ .Date | time.Format ":date_long" }}`.
Not sure if that introduces other issues.

This automatically formats the date according to locale, so `March 13, 2023` -> `13. März 2023`.

The feature was available since version 0.87 from August 3, 2021 (https://gohugo.io/news/0.87.0-relnotes/).
Current Debian 11 stable contains 0.80.0, but has version 0.104.3-1 in backports.

**Comment by Vimux** [comment]
I'm aware of this feature but haven't looked closely yet. If this is a breaking change, which is very likely, it won't be accepted unless I want to add another significant breaking change, which is very rare. I have no plans to close the issue or to work on it soon.

If anyone has ideas for backward-compatible implementations, comments are always welcome.

**Comment by Vimux** [comment]
I checked this out again yesterday. It doesn't seem to be as bad as I first thought. It doesn't break old versions of Hugo with some critical error message, so bumping the minimal Hugo version isn't necessary. We can also keep old defaults without any problems. So what's the problem? The main problem is that if you already have a multilingual site, such changes will be applied automatically when the theme is updated. If your datetime like "January 2, 2006", then it would be localized. Is it a bug fix or a breakable change? I think it's a fix because the months should be in the same language as the other lines, but other people may feel differently.

There's another concern, what if you need to use English date time for another language? After this change, this will no longer be possible by default. On the other hand, it was impossible to use anything other than English by default before. **Maybe there's probably something else I've inadvertently missed**.

I'm planning to do a PR when I get around to it, but I need to think about the "break or fix" situation and how to document it carefully.
